spring.application.name=clinica

# Datasource Configuration 
# ?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC  poner este pedazo luego de clinica_db para la u
spring.datasource.url=jdbc:mysql://localhost:3306/clinica_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8081
spring.jpa.properties.hibernate.format_sql=true


# JPA / Hibernate: genera las tablas a partir de las entidades
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# En src/main/resources/application-dev.properties
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Deshabilitar el manejo de archivos estáticos para estas rutas
spring.mvc.static-path-pattern=/public/**
spring.web.resources.add-mappings=false